sources:
  - name: raw
    schema: gz_raw_data
    tables: 
      - name: sales 
        identifier: raw_gz_sales
        description: sales data for greenweez company
        loaded_at_field: cast(date_date as TIMESTAMP)
        freshness: 
          warn_after:
            count: 90
            period: day
        columns:
         - name: date_date
           description: date for orders
           tests: 
             - not_null
         - name: orders_id
           tests: 
             - not_null
         - name: pdt_id
           tests: 
             - not_null
         - name: revenue
           tests:
             - not_null
         - name: quantity
           tests:
             - not_null
        tests: 
         - unique:
            column_name: 'orders_id || pdt_id' 

      - name: ship 
        identifier: raw_gz_ship
        columns: 
         - name: orders_id
           tests: 
                  - not_null
                  - unique
         - name: shipping_fee 
           tests: 
                 - not_null
         - name: shipping_fee_1
           tests:
                  - not_null
         - name: logCost 
           tests: 
                 - not_null
         - name: ship_cost
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests: 
                 - not_null
                 - unique
          - name: purchSE_PRICE
            tests:
                 - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaigns
        columns:
          - name: date_date
            tests: 
              - not_null
          - name: paid_source 
            description: show us what is the campaign source
            tests:
              - not_null
          - name: campaign_key 
            description: campaign key
            tests:
              - not_null
          - name: camPGN_name 
            description: campaign name
            tests:
              - not_null
          - name: ads_cost
            description: cost values based on campaign
            tests:
              -  not_null
          - name: impression 
            description: impression values based on campaign
            tests:
              - not_null
          - name: click
            description: impression values based on campaign
            tests:
              - not_null
        tests:
          - unique:
             column_name: 'date_date || campaign_key'
      - name: bing
        identifier: raw_gz_bing
        description: bing campaigns 
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            description: show us what is the campaign source 
            tests:
              - not_null
          - name: campaign_key 
            description: campaign key
            tests:
              - not_null
          - name: camPGN_name 
            description: campaign name
            tests:
              - not_null
          - name: ads_cost
            description: cost values based on campaign
            tests:
              -  not_null
          - name: impression 
            description: impression values based on campaign
            tests:
              - not_null
          - name: click
            description: impression values based on campaign
            tests:
              - not_null
        tests:
          - unique:
             column_name: 'date_date || campaign_key'
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaigns
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            description: show us what is the campaign source 
            tests:
              - not_null
          - name: campaign_key 
            description: campaign key
            tests:
              - not_null
          - name: camPGN_name 
            description: campaign name
            tests:
              - not_null
          - name: ads_cost
            description: cost values based on campaign
            tests:
              -  not_null
          - name: impression 
            description: impression values based on campaign
            tests:
              - not_null
          - name: click
            description: impression values based on campaign
            tests:
              - not_null
        tests:
          - unique:
             column_name: 'date_date || campaign_key'
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaigns
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            description: show us what is the campaign source 
            tests:
              - not_null
          - name: campaign_key 
            description: campaign key
            tests:
              - not_null
          - name: camPGN_name 
            description: campaign name
            tests:
              - not_null
          - name: ads_cost
            description: cost values based on campaign
            tests:
              -  not_null
          - name: impression 
            description: impression values based on campaign
            tests:
              - not_null
          - name: click
            description: impression values based on campaign
            tests:
              - not_null
        tests:
          - unique:
             column_name: 'date_date || campaign_key'
      

            
        
 