sources:
  - name: raw
    schema: gz_raw_data
    tables: 
      - name: sales 
        identifier: raw_gz_sales
        description: sales data for greenweez company
        loaded_at_field: cast(date_date as TIMESTAMP)
        freshness: 
          warn_after:
            count: 90
            period: day
        columns:
         - name: date_date
           description: date for orders
           tests: 
             - not_null
         - name: orders_id
           tests: 
             - not_null
         - name: pdt_id
           tests: 
             - not_null
         - name: revenue
           tests:
             - not_null
         - name: quantity
           tests:
             - not_null
        tests: 
         - unique:
            column_name: 'orders_id || pdt_id' 

      - name: ship 
        identifier: raw_gz_ship
        columns: 
         - name: orders_id
           tests: 
                  - not_null
                  - unique
         - name: shipping_fee 
           tests: 
                 - not_null
         - name: shipping_fee_1
           tests:
                  - not_null
         - name: logCost 
           tests: 
                 - not_null
         - name: ship_cost
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests: 
                 - not_null
                 - unique
          - name: purchSE_PRICE
            tests:
                 - not_null
                 
        
 